data:
  augmentation:
    center_crop: true
    center_crop_ratio: 0.9

model:
  diffusion_steps: 6
  scheduler_type: "flow_match"

eval:
  finetuned_checkpoint: "/home/dm/QWENLA/VLANeXt_migration/VLANeXt/checkpoints/VLANeXt_vita_blockwise4/12_24_mq16_dim1024_flow8_ae6_dct_div_libero_long/checkpoint_6000.pt"
  task_suite_name: "libero_10"
  num_steps_wait: 10
  num_steps_execute: 8
  num_trials_per_task: 50
  seed: 42
  image_size: 256
  save_video: true
  save_video_every: 1
  resume_episodes: 0
  resume_successes: 0
